- hosts: tag_Environment_Development

  tasks:
    - name: install apache
      yum: name=httpd state=present

    - name: configure static web page
      copy: 
        src: /var/lib/jenkins/workspace/development-deploy/static-web/
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0644

    - name: restart apache
      service: name=httpd state=restarted
